### ISSUE TITLE
Question about runnableExamples

### ISSUE THREAD

**Issue by kaushalmodi** [narimiran/itertools#2]
Hello,

I am learning Nim, and I happened to come across this module of yours. 

I am curious why you have the runnableExamples in your procs.. won't those run each time someone uses `count` and other procs in this modules?

If they don't run each time as I think, then how so?

**Comment by narimiran** [comment]
RunnableExamples are part of a documentation, to provide both an examle of using a function and serving as a test which is run only when creating the documentation.

They will not run when you're using the functions.

I hope this answers your questions. If not, please reopen this issue and/or write a comment.

**Comment by kaushalmodi** [comment]
Thank you. I was misreading `runnableExamples:` as a `block`.
