### ISSUE TITLE
Possible nim version of permutations()

### ISSUE THREAD

**Issue by zetashift** [narimiran/itertools#3]
Heya, I've been working through rosalind.info exercises and a few are easily solvable by a default permutations function. I failed to solve it with nim because I'm not smart enough and ended up with using Scala's permutations function.
After I solved it I went through the solutions and everybody used the permutations function from python itertools. I was wondering if this lib will support such a thing/best way to go at it would be.

For one of the exercises I did make a recursive solution thanks to rosettacode:
```nim
proc permutations(ls: openArray[int], emit: proc(emit: openArray[int])) =
    var s = @ls
    if s.len == 0:
        emit(s)
        return
    
    var rc: proc(np: int)
    rc = proc(np: int) =
        if np == 1:
            emit(s)
            return
        var
            np1 = np-1
            pp = s.len - np1
        rc(np1)
        for i in countdown(pp, 1):
            swap s[i], s[i-1]
            rc(np1)
        let w = s[0]
        s[0..pp-1] = s[1..pp]
        s[pp] = w
    rc(s.len)
```

**Comment by narimiran** [comment]
Combinatoric iterators (product, permutations, combinations, combinations with replacement) are still missing from this library as I'm not sure what would be the best way to implement them.

I have already written `permutations` iterator (non-recursive, btw), but in its current version (not published) it only gives you *all* permutations if your input is sorted (or I sort it inside of the iterator). I'm still thinking what's the best way to approach this.

I hope to catch some free time in the following weeks and see what it can be done about these combinatoric iterators.

**Comment by zetashift** [comment]
If you need any help, I'd love to help with this!
Should I close this issue for now?

**Comment by narimiran** [comment]
> Should I close this issue for now?

No, leave it open as a reminder to myself that I need to work on this.

**Comment by narimiran** [comment]
I've been playing with the implementation of `permutations` and I've run into some interesting questions:

1. If you have a container with duplicates, e.g. `"abbc"`, should you consider those duplicates as separate/different? Should permutations of `"abbc"` be: 
    * `abbc, abcb, abbc, abcb, acbb, acbb, ...` (this is how Python's `itertools.permutations` works, notice there are only three distinct permutations),
    * `abbc, abcb, acbb, babc, bacb, bbac, ...` (this is how Nim's `algorithm.nextPermutation` works)?

    Consider the extreme example `"aaaa"`. Would you like to see 24 permutations (all of them the same) like Python does, or only one like Nim does?

2. If you have a container which is not pre-sorted (e.g. `"bac"`), which one of these behaviours would you expect (and which one would you tolerate if documented :)):
    * `bac, bca, abc, acb, cba, cab` (Python's `permutations`: all permutations, starting from the input),
    * `bac, bca, cab, cba` (Nim's `nextPermutation`: just 'remaining' permutations, stops when the permutation is in decreasing order),
    * `abc, acb, bac, bca, cab, cba` (sorting it first then sending it to Nim's `nextPermutation`, notice that permutations are *not* just 'shifted' from Python version: the order is different (e.g. see what follows after `"acb"` in each version))?

**Comment by PMunch** [comment]
1. I prefer Nim's way. You're most likely to throw it in a loop and do some calculation based on the permutation, this would mean you're doing much more work for each duplicate if you forget to sort them out.

2. Again I really like Nim's way here as well. It's called `nextPermutation` and it makes sense that the argument is a given "state". Building on my previous assumption that you're throwing this in a loop the order of the generated permutations doesn't really matter.

**Comment by zetashift** [comment]
I don't mind either way, as long as there is a comment saying how it works!
I used the Scala version of permutation(so I don't know how Python's permutation exactly works) to solve it: https://www.scala-lang.org/api/2.12.3/scala/collection/immutable/List.html#permutations:Iterator[Repr] and this worked fine to solve both exercises about permutations. However in both exercises I did not have the issue of duplicates really and I did not have to sort before permutating, only after.

Also PMunch logic makes sense and it's the Nim way™. I don't mind either as long as it explains how it works!

**Comment by narimiran** [comment]
> I used the Scala version of permutation(so I don't know how Python's permutation exactly works) to solve it: https://www.scala-lang.org/api/2.12.3/scala/collection/immutable/List.html#permutations:Iterator[Repr]

The example there with `"abb"` shows that Scala seems to be similar to Nim when it comes to (1).

Regarding (2): what is the result from Scala for `"bac".permutations`?

**Comment by Vindaar** [comment]
Regarding 1:
  If it's a choice between two, I would prefer Nim's way, since the same character is not distinct and therefore a switch between them shouldn't count.
However, I think there should be an option like `skipDuplicates` or something like that (with the default being to skip them).

For number 2:
Imo it mainly depends on what the procedure is named so it provides what one would naively expect. For Nim's `nextPermutation` it imo makes perfect sense, as @PMunch explained. If the name of the proc is just `permutations` however, it's less clear. 
Personally I'd make `permutations` also have an additional parameter, where the default then is "sorting before" and then permutation in the sense you list last. 
Regarding the different orderings of permutations in Nim and Python: I'd never rely on a specific order in which the permutations appear in such a proc, so that's a non-issue in my book.

**Comment by zetashift** [comment]
> Regarding (2): what is the result from Scala for `"bac".permutations`?

I get ```bac, bca,abc, acb, cba, cab``` when using permutations on `bac`.

**Comment by narimiran** [comment]
Thank you guys for the feedback!

My current idea is to have two iterators:
* `distinctPermutations`, which will give you sorted permutations without duplicates (to give you what  you would expect by repeatedly calling `algorithm.nextPermutation`)
* `permutations`, similar to Python's version: with duplicates and preserving the original order (to not surprise users coming from Python)

For example:

```nim
let a = "bab"

for x in a.distinctPermutations():
  echo x

echo "\n---\n"

for x in a.permutations():
  echo x
```

```
@['a', 'b', 'b']
@['b', 'a', 'b']
@['b', 'b', 'a']

---

@['b', 'a', 'b']
@['b', 'b', 'a']
@['a', 'b', 'b']
@['a', 'b', 'b']
@['b', 'b', 'a']
@['b', 'a', 'b']
```

Thoughts?

**Comment by narimiran** [comment]
Ok, I released a new version which now contains these combinatoric iterators:

* product
* distinctPermutations
* permutations
* combinations

I hope this now closes this issue. (If not, please reopen it)
