### ISSUE TITLE
Implement chunked/windowed iterators

### ISSUE THREAD

**Issue by LemonBoy** [narimiran/itertools#5]
They're not part of the official itertools but they're very useful nonetheless:

- [chunked_iter](https://boltons.readthedocs.io/en/latest/iterutils.html#boltons.iterutils.chunked_iter)
- [windowed_iter](https://boltons.readthedocs.io/en/latest/iterutils.html#boltons.iterutils.windowed_iter)

Keep up the good work!

**Comment by narimiran** [comment]
Thanks for the links! The whole `iterutils` looks interesting (this is the first time I hear about it), I'll see what else can I implement.

**Comment by narimiran** [comment]
Now there are not only `chunked` and `windowed`, but also `pairwise` and `unique` :smiley:
